# Generated by Django 5.0.4 on 2024-05-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=30)),
                ('product_description', models.TextField()),
                ('product_type', models.CharField(max_length=20)),
                ('product_link', models.TextField()),
                ('keywords', models.TextField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
